import{S as u,i as l}from"./assets/vendor-8c59ed88.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const d=document.getElementById("searchBar"),p=document.getElementById("searchForm");document.getElementById("myButton");const c=document.querySelector(".search-bar"),y="33885109-a6cb8296a367a3cf09d2759c8";c.style.display="flex";c.style.justifyContent="center";c.style.gap="20px";const n=document.querySelector(".gallery"),f=new u(".gallery a");function m(){selectors.container.innerHTML=""}function h(a){if(m(),a.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}a.hits.forEach(e=>{const o=document.createElement("li");o.innerHTML=`
                                    <a href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
                                      <img src="${e.webformatURL}" id = "myImage" alt="${e.tags}" width = "360" />
                                    </a>
                                    <div class="info">
                                      <span>Likes: ${e.likes}</span>
                                      <span>Views: ${e.views}</span>
                                      <span>Comments: ${e.comments}</span>
                                      <span>Downloads: ${e.downloads}</span>
                                    </div>
                                  `,n.appendChild(o),n.style.display="flex",n.style.flexWrap="wrap",n.style.justifyContent="center",n.style.gap="40px",n.style.marginTop="20px",o.classList.add("my-list")}),f.refresh()}p.addEventListener("submit",a=>{a.preventDefault();const e=d.value.trim();if(e===""){l.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}const o=new URLSearchParams({key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0});fetch(`https://pixabay.com/api/?${o}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).then(s=>h(s)).catch(s=>{l.error({title:"Error",message:`An error occurred: ${s}`})})});
//# sourceMappingURL=commonHelpers.js.map
