import{S as u,i}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const d=document.getElementById("search"),p=document.getElementById("myButton"),l=document.querySelector(".search-bar"),y="33885109-a6cb8296a367a3cf09d2759c8";l.style.display="flex";l.style.justifyContent="center";l.style.gap="20px";const o=document.querySelector(".gallery"),f=new u(".gallery a");function m(){o.innerHTML=""}function h(n){if(m(),n.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}n.hits.forEach(t=>{const r=document.createElement("li");r.innerHTML=`
                                    <a href="${t.largeImageURL}" data-lightbox="gallery" data-title="${t.tags}">
                                      <img src="${t.webformatURL}" id = "myImage" alt="${t.tags}" width = "360" />
                                    </a>
                                    <div class="info">
                                      <span>Likes: ${t.likes}</span>
                                      <span>Views: ${t.views}</span>
                                      <span>Comments: ${t.comments}</span>
                                      <span>Downloads: ${t.downloads}</span>
                                    </div>
                                  `,o.appendChild(r),o.style.display="flex",o.style.flexWrap="wrap",o.style.justifyContent="center",o.style.gap="40px",o.style.marginTop="20px",r.classList.add("my-list")}),f.refresh()}p.addEventListener("click",()=>{const n=d.value.trim();if(n===""){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}const t=new URLSearchParams({key:y,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0});fetch(`https://pixabay.com/api/?${t}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>h(r)).catch(r=>{i.error({title:"Error",message:`An error occurred: ${r}`})})});
//# sourceMappingURL=commonHelpers.js.map
